### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by bestwestern** [storybooks/storybook-deployer#4]
I am probably doing something very wrong..
I did this:
1. I cloned the very simple demo
2. npm i
3. npm i --save @kadira/storybook-deployer
4. Added "deploy-storybook": "storybook-to-ghpages" 
5. npm run deploy-storybook

And got the attached npm-debug.log
[npm-debug.pdf](https://github.com/kadirahq/storybook-deployer/files/422196/npm-debug.pdf)

**Comment by ecmadao** [comment]
When I use "storybook-to-ghpages" command to publish I had same problem too.
So I looked into story-deployer source code, and found they create a series of git shell command to commit and publish.
I tried to use these cmd to repeat the Error, but every step I had no permission to exec. So the solution is, **give your project folder and all of it's files & folders full permission**, at least this solved my problem. @bestwestern

**Comment by UsulPro** [comment]
To start using `storybook-deployer` you need to add it as `devDependency` to a repo with Storybook installed. See [readme](https://github.com/storybooks/storybook-deployer) for details.

@bestwestern Looks like you run it on Windows. At this moment Windows isn't supported because of #11. Going to fix it
